### ISSUE TITLE
ImportError: module 'keyserv.config' has no attribute '<flask'

### ISSUE THREAD

**Issue by reezalaq** [miniCruzer/mini-key-server#1]
Entered : flask create-user username password
and received below error messages ..

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 515, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 254, in locate_app
    return find_best_app(script_info, module)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 76, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/cli.py", line 114, in call_factory
    return app_factory(script_info)
  File "/Users/reezalaq/Documents/mini-key-server-master/keyserv/__init__.py", line 51, in create_app
    app.config.from_object("keyserv.config.{}".format(config))
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/flask/config.py", line 170, in from_object
    obj = import_string(obj)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/_compat.py", line 137, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 431, in import_string
    module = import_string(module_name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/_compat.py", line 137, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 431, in import_string
    module = import_string(module_name)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/_compat.py", line 137, in reraise
    raise value.with_traceback(tb)
  File "/Users/reezalaq/Documents/mini-key-server-master/venv/lib/python3.6/site-packages/werkzeug/utils.py", line 436, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'keyserv.config.<flask.cli.ScriptInfo object at 0x10fdc7d30>'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'keyserv' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/__init__.py'.
- 'keyserv.config' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/config.py'.
- 'keyserv.config.<flask' not found.

Original exception:

ImportStringError: import_string() failed for 'keyserv.config.<flask.cli'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'keyserv' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/__init__.py'.
- 'keyserv.config' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/config.py'.
- 'keyserv.config.<flask' not found.

Original exception:

ImportStringError: import_string() failed for 'keyserv.config.<flask'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'keyserv' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/__init__.py'.
- 'keyserv.config' found in '/Users/reezalaq/Documents/mini-key-server-master/keyserv/config.py'.
- 'keyserv.config.<flask' not found.

Original exception:

ImportError: module 'keyserv.config' has no attribute '<flask' @miniCruzer

**Comment by furas** [comment]
I found problem. It is 

`export FLASK_APP=keyserv.py`

It should be 

`export FLASK_APP=keyserver.py`

with `er` at the end.
